### PR TITLE
Add {post,pre}-link scripts to automatically activate

### PR DESCRIPTION
**Pull request by xhochy**
Based on https://github.com/conda-forge/widgetsnbextension-feedstock

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
@xhochy: Thanks! Are you sure that is required? Even without: both test commands list the extension either as enabled `jupyter labextension list` and build it also `jupyter lab build`, which is afaik only done for enabled extensions.

I have situations, where the extensions does not work for unknown reasons. Maybe the post-link/pre-unlink scripts are required for that. They are certainly no harm and can only improve the situation.

**Comment by xhochy** [comment]
@dbast I'm debugging this a bit. For me the relevant thing is that it should show up in `jupyter serverextension list`. 

I'm wondering a bit about the `--no-build` flag in`"${PREFIX}/bin/jupyter" labextension install . --no-build`. Why aren't we running the build during the package build?

**Comment by dbast** [comment]
This is a hybrid extension containing the server/backend part (python) and also the frontend part (Javascript). The `--no-build` is applied to the Javascript part. `tree` of the package looks like:
```
.
├── info
│   ├── LICENSE.txt
│   ├── about.json
│   ├── files
│   ├── git
│   ├── hash_input.json
│   ├── index.json
│   ├── link.json
│   ├── paths.json
│   ├── recipe
│   │   ├── bld.bat
│   │   ├── build.sh
│   │   ├── conda_build_config.yaml
│   │   ├── meta.yaml
│   │   └── meta.yaml.template
│   └── test
│       ├── run_test.bat
│       ├── run_test.py
│       └── run_test.sh
├── share
│   └── jupyter
│       └── lab
│           └── extensions
│               └── jupyterlab-git-0.5.0-3b4015cbd7491318616e273ea3d521b332476a78.tgz
└── site-packages
    ├── jupyterlab_git
    │   ├── README.md
    │   ├── __init__.py
    │   ├── git.py
    │   └── handlers.py
...
```

The JS part cannot be compiled and put into the package as the nodejs compile output is not separatable by extension.... It is all together. (try to build the package without no-build and inspect the content).

The way how this package is build, is combining three things:
* hybrid: server/backend (python) + frontend (JS) in one package
* noarch: `noarch: python` + `--no-build`, everything else is anyway afaik not possible for JupyterLab extensions
* auto-enabled without pre/post scripts: the `nodejs` run-time dependency allows js frontend compilation on Jupyterlab start when the new extension is detected and can be compile together with all other extensions including webpack bundling etc.

See also 
* https://github.com/conda-forge/conda-forge.github.io/issues/761
* https://jupyterlab.readthedocs.io/en/stable/user/extensions.html

@xhochy Does this answer your questions?

@blink1073 Please correct me, if the above details are different.

**Comment by blink1073** [comment]
The server extension can be auto-enabled by following this pattern (in the source repo):

https://github.com/matplotlib/jupyter-matplotlib/blob/3d43a36443886a9aa1492530e776f8f531c8c3bf/jupyter-matplotlib.json
 https://github.com/matplotlib/jupyter-matplotlib/blob/3d43a36443886a9aa1492530e776f8f531c8c3bf/jupyter-matplotlib.json

The lab extension can be installed (but not built, that has to be done on the user's machine to make the single app), by following this pattern (and the `cmdclass` handlers as well):
https://github.com/matplotlib/jupyter-matplotlib/blob/3d43a36443886a9aa1492530e776f8f531c8c3bf/setup.py#L72

**Comment by xhochy** [comment]
@blink1073 Thank you for these hints. I will in addition to this PR try to add the changes upstream to make this package and some others simpler to package.

@dbast I look deeper into this and am confused that this is working for you without the server extension. The `serverextension enable` command activates the `/git/` endpoint on the jupyterlab server which is needed to handle all git operations in the backend.

**Comment by dbast** [comment]
I started to test this, but somehow it does not help to get the extension working in those situations where it currently does not work here with the error `You aren’t in a git repository.`. There are also upstream issues about that...

@xhochy The extension is working for you with this PR included and before it was not? Or what was the reason to come up with the PR?

**Comment by xhochy** [comment]
@dbast Yes, I need the command in these link scripts to get the extension working for me.

**Comment by dbast** [comment]
Ok. Thought the scripts are redundant, but seems not. Maybe that get fixed upstream in the future.

Sorry, for keeping you waiting. Merging this then. Many thanks!

**Pull request merged**
