### PR TITLE
Possible workaround for #1

### LINKED ISSUE #1: Remove `nodejs` from `run` dependency
Dear maintainers,

Is there a particular reason why `nodejs` is a `run` dependency of this package?

https://github.com/conda-forge/jupyterlab-git-feedstock/blob/f09d8fb70bd711225ea6eb309241d7ea0e228342/recipe/meta.yaml#L25-L30

In use case where administrators don't want users to add jupyterlab extensions, a solution is to ship JupyterLab with prepackaged extensions and without nodeJS. Therefore it would be nice to remove it from this great extension.

### PR DESCRIPTION
**Pull request by fcollonval**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #1 

Come back on the discussion of #1 to have a version packaging the server extension without `nodejs` as run dependency.

The workaround proposed is based on [`matplotlib` recipe](https://github.com/conda-forge/matplotlib-feedstock) that packages matplotlib with (`matplotlib` package) and without Qt (`matplotlib-base` package) in a single recipe reducing maintenance burden.

### CODE REVIEW

**Comment by fcollonval** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
So this splits the package into two packages. like backend and frontend. But neither the backend nor the frontend work without the other (that is afaik different for `matplotlib{-base}`). 

Can you explain what that really is intended to solve or in which situation that helps?

**Comment by dbast** [comment]
´nodejs´ remains to be a run dependency of the frontend...

**Comment by fcollonval** [comment]
Hey @dbast,

Actually the graph dependency is unidirectional. The frontend needs the backend. But the backend works without the frontend (possible use cases: use in another frontend or use of backend class in other server extensions).

The results of this proposal are two packages `jupyterlab-git-server` that contains all the code (as the previous extension) and `jupyterlab-git` that pins `jupyterlab-git-server` as dependency and needs `nodejs` as run dependency. So the behavior `conda install jupyterlab-git` stays the same.

The following picture presents the two packages, on the left the `server` one and on the right the user friendly `jupyterlab-git` (I open the recipe for the latter to highlight the run dependencies).

image

What do you think?

**Comment by fcollonval** [comment]
I modify a bit the proposal to ship the lab extension only in the `jupyterlab-git` package. And correct the recipe so both packages are `noarch`.

**Comment by fcollonval** [comment]
I tested locally. It works as expected, meaning:

*  `conda install jupyterlab-git` behaves exactly as previously (the new change is its dependency on `jupyterlab-git-server`)
* `conda install jupyterlab-git-server` installs only the server extension

**Comment by fcollonval** [comment]
nodejs is no more needed for JupyterLab 3 - closing this following #36

**Pull request closed without merging**
