### PR TITLE
Correct run dependencies

### PR DESCRIPTION
**Pull request by fcollonval**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] ~Ensured the license file is being packaged.~

Set dependencies to be coherent with package requirement.

### CODE REVIEW

**Comment by fcollonval** [comment]
@conda-forge-admin, please rerender

**Comment by blink1073** [comment]
Error looks legit:

SHA256 mismatch: '17b3c57c5ed1369deb5b7a63edb9b9b2caa762f7ea951df061346bfc1857e5be' != 'ed7f54460bb987d0b2c8c81010a41d603783b8e7e1d32a2ca10102e85e7d1de7'

**Comment by dbast** [comment]
Just had a look ... 0.8.0 was released 8 days ago and updated 6 days ago without any version number increment to e.g. 0.8.X... that is why the sha256 also changed. Not very reproducible.

**Comment by dbast** [comment]
@fcollonval Thanks!

**Comment by fcollonval** [comment]
Thank you both for the quick correction.
@jaipreet-s, could you confirm that the git tag was set to another commit?

**Pull request merged**
